### ISSUE TITLE
Is there documentation on the available options?

### ISSUE THREAD

**Issue by philipwalton** [stereobooster/jekyll-press#12]
The README shows the following for the _config.yml file, but it's not clear to me what the possible options are.

```
jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
```

Is this documented anywhere? I looked in the code and I couldn't see any places that made use of these. I checked the html_press repo, but it didn't have any documentation either.

Thanks.
