### ISSUE TITLE
Not sure how to implement

### ISSUE THREAD

**Issue by nthnclrk** [stereobooster/jekyll-press#14]
Hey, I'm having trouble understanding the README. Just looking for clarification for what the contents of the actual .rb file should look like.

I chose the Standalone option..

Here's what I've done:

Installation: Fine. Easily installed the gem

Usage: You instruct to create the following:

```
# _plugins/jekyll-press-plugin.rb
require 'jekyll-press'
```

So I created a ruby file in my _plugins folder with the contents

```
require 'jekyll-press'
```

I was sure this wasn't correct, so I then tried to append the previous content with the settings as shown in the README:

```
jekyll-press:
exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of     file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
```

Which led me to a .rb file with the following contents:

```
require 'jekyll-press'
jekyll-press:
exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of     file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
```

I'm certain this isn't correct, but I'm not sure of what I need to do. Sorry to be a massive noob, but I can't seem to find answer anywhere else.
